# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bytes <- function(int_vec) {
    .Call(`_sort_bytes`, int_vec)
}

fstsort <- function(int_vec) {
    .Call(`_sort_fstsort`, int_vec)
}

fstsort_radix_int <- function(int_vec) {
    .Call(`_sort_fstsort_radix_int`, int_vec)
}

fstsort_radix_logical <- function(logical_vec) {
    .Call(`_sort_fstsort_radix_logical`, logical_vec)
}

fstsort_radix_logical_order <- function(logical_vec, order) {
    .Call(`_sort_fstsort_radix_logical_order`, logical_vec, order)
}

fstmergesort <- function(int_vec_left, int_vec_right) {
    .Call(`_sort_fstmergesort`, int_vec_left, int_vec_right)
}

fstsort_combined <- function(int_vec) {
    .Call(`_sort_fstsort_combined`, int_vec)
}

getnrofthreads <- function() {
    .Call(`_sort_getnrofthreads`)
}

setnrofthreads <- function(nrOfThreads) {
    .Call(`_sort_setnrofthreads`, nrOfThreads)
}

hasopenmp <- function() {
    .Call(`_sort_hasopenmp`)
}

restore_after_fork <- function(restore) {
    invisible(.Call(`_sort_restore_after_fork`, restore))
}

